wifi:
  ssid: !secret iot_ssid
  password: !secret iot_password

  ap:
    ssid: "${friendly_name} ESP"
    password: !secret fallback_password

captive_portal:

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome

web_server:
  port: 80
  version: 3

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 120s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
